actors:
  kirameister:
    image_url: /images/actors/alice.png
    name: kirameister
    url: http://twitter.com/kirameister_
  bob:
    image_url: /images/actors/bob.png
    name: bob
    url: http://sns.example.com/bob
author: kirameister
description: 10回続けられたらタイトル考えます
description_long: Example long description
email: info@example.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: examplehashtag
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Europe/Berlin
title: 10回続けられたらタイトル考えます
url: https://kirameister.github.io/
